################################################## 
# WS4PM_server.py
# generated by ZSI.generate.wsdl2python
##################################################

from ZSI.schema import GED
from WS4PM_services_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
getConfigInfosRequest = GED("http://ws4pm.communesplone.org", "getConfigInfosRequest").pyclass
getConfigInfosResponse = GED("http://ws4pm.communesplone.org", "getConfigInfosResponse").pyclass
getItemInfosRequest = GED("http://ws4pm.communesplone.org", "getItemInfosRequest").pyclass
getItemInfosResponse = GED("http://ws4pm.communesplone.org", "getItemInfosResponse").pyclass
searchItemsRequest = GED("http://ws4pm.communesplone.org", "searchItemsRequest").pyclass
searchItemsResponse = GED("http://ws4pm.communesplone.org", "searchItemsResponse").pyclass
createItemRequest = GED("http://ws4pm.communesplone.org", "createItemRequest").pyclass
createItemResponse = GED("http://ws4pm.communesplone.org", "createItemResponse").pyclass

# Service Skeletons
class WS4PM(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_getConfigInfos(self, ps, **kw):
        request = ps.Parse(getConfigInfosRequest.typecode)
        return request,getConfigInfosResponse()

    def soap_getItemInfos(self, ps, **kw):
        request = ps.Parse(getItemInfosRequest.typecode)
        return request,getItemInfosResponse()

    def soap_searchItems(self, ps, **kw):
        request = ps.Parse(searchItemsRequest.typecode)
        return request,searchItemsResponse()

    def soap_createItem(self, ps, **kw):
        request = ps.Parse(createItemRequest.typecode)
        return request,createItemResponse()

    soapAction['http://ws4pm.communesplone.org/getConfigInfos'] = 'soap_getConfigInfos'
    root[(getConfigInfosRequest.typecode.nspname,getConfigInfosRequest.typecode.pname)] = 'soap_getConfigInfos'

    soapAction['http://ws4pm.communesplone.org/getItemInfos'] = 'soap_getItemInfos'
    root[(getItemInfosRequest.typecode.nspname,getItemInfosRequest.typecode.pname)] = 'soap_getItemInfos'

    soapAction['http://ws4pm.communesplone.org/searchItems'] = 'soap_searchItems'
    root[(searchItemsRequest.typecode.nspname,searchItemsRequest.typecode.pname)] = 'soap_searchItems'

    soapAction['http://ws4pm.communesplone.org/createItem'] = 'soap_createItem'
    root[(createItemRequest.typecode.nspname,createItemRequest.typecode.pname)] = 'soap_createItem'
